### ISSUE TITLE
Changes in an IIA already approved by both parties

### ISSUE THREAD

**Issue by susanaUal** [erasmus-without-paper/ewp-specs-api-iias#83] opened 2022-05-20 12:31 UTC
We have an IIA at the test environment approved by both parties. In one of the cooperation conditions:

- Now we have **3 mobilities per year** (**from 2021-22 to 2022-23**) 
- We would like to make a change to **9 mobilities per year** (**from 2023-24**).

We have sent a CNR because the IIA has change but how should we represent this at our IIA GET API? 
Should represent only the last situation or should represent both situations?

**Comment by kamil-olszewski-uw** [comment] 2022-05-20 13:54
First, you should contact the partner university and explain the situation so that they know you intend to take this action. First of all, you should find out from the partner university whether their system allows you to re-approve IIA that has already been approved. If so, just modify the cooperation conditions of the existing agreement, send the CNR, and when the partner updates the IIA on their side, approve each other's copy of IIA once again.

If the partner cannot approve the same IIA again for technical reasons, you will probably need to create a new IIA and go through the entire data exchange and approval procedure with the partner again and remove the old IIA from the system.

**Comment by susanaUal** [comment] 2022-05-24 09:09
If we decide that it's the same IIA, how do we reflect that the same mobility has different conditions depending on the academic year? On this example it would be:

- 3 mobilities per year (from 2021 to 2022-23)
- 9 mobilities per year (from 2023-24 onwards)

**Comment by kamil-olszewski-uw** [comment] 2022-05-25 11:28
If your system and partner system allow it, you can modify the list of academic terms of current cooperation conditions, create new cooperation conditions with the number of mobilities set to 9, and then again mutually approve IIA.

Or, you can create a new IIA and mutually approve it.

It is currently not possible to automatically terminate IIAs prior to the predetermined end academic term. Any such activity requires communication outside of EWP. We plan to change this in the future.

**Comment by umesh-qs** [comment] 2022-05-26 15:21
> If your system and partner system allow it, you can modify the list of academic terms of current cooperation conditions, create new cooperation conditions with the number of mobilities set to 9, and then again mutually approve IIA.
> 
> Or, you can create a new IIA and mutually approve it.
> 
> It is currently not possible to automatically terminate IIAs prior to the predetermined end academic term. Any such activity requires communication outside of EWP. We plan to change this in the future.

This should not be system specific. We cannot have a design where one provider does not allow re-approval and other provider allow it. This has to be fixed at IIA design level.

**Comment by umesh-qs** [comment] 2022-05-29 14:39
@janinamincer-daszkiewicz  sooner this is clarified and fixed, better it is for the universities to adopt to EWP ways of agreements.

**Comment by janinamincer-daszkiewicz** [comment] 2022-05-29 14:48
There is a plan to handle changes in IIAs, but first it has to be discussed among Business Process Owners, then passed to designers and developers. This will not happen quickly, I would rather assume that in the beginning of 2023 we may be ready with the changes.

**Comment by umesh-qs** [comment] 2022-05-30 04:19
I assume it means that, till then HEIs will continue to face issues with IIA exchange.

**Comment by demilatof** [comment] 2022-08-21 22:52
My 2 cents on this issue that impacts not only the EWP infrastructure, but even our internal system.
I think we have to consider the cooperation condition hash: if it is different or not, because in the first case we are changing values that are really important for nominations (e.g. "mobilities-per-year"), that could be opened or already accepted. If the cooperation condition hash is not changed,  the modified values should not be so important for the nominations.
Therefore, I think that if the changes don't alter the cooperation condition hash we can stay with the usual procedure (IIA CNR - GET - APPROVAL). 

BUT if the changes concern the cooperation conditions and their hash code, then we may have a critical situation.
The problem is that in our system the same IIA ID should identify both the approved IIA and the new IIA modified by only a partner.
This means that we are offering a number of mobilities (for example) whilst the partner wants to reduce this number.
If we accept this situation we may have problem to identify, retrieve and differentiate what we have approved with an IIA Get.

In my opinion the most conservative solution is to forbid to change the cooperation conditions (except contacts) for an approved IIA.
If the X partner wishes to modify something that changes the hash code for an approved IIA it should send to the Y partner an IIA Closing CNR that contains the IIA IDs of both partners and the last academic year of validity of the already approved IIA. 
If the Y partner agrees to close the approved IIA for that year it sends to X partner an IIA Closing Approval with the IIA IDs of both partners and the same academic year received with IIA Closing CNR; the X partner checks if for those IIA IDs the last academic year is correct (the one it proposed, with IIA Closing CNR) and it answers with HTTP 200 status and an empty response if the last academic year is the same. If the academic year is changed, the X partner answers with HTTP 400 Error.
If the Y partner receives HTTP 200 status the IIA is closed starting from the specified academic year and the following IIA Get Responses (of both partners) should provide two new elements inside the IIA element (so that the hash code is still the same), for example after <in-effect>true</in-effect>:

- last-academic-year (the same accepted by X and Y partners)
- closing-date (for archiving purpose, the date in which X partner answered Y with HTTP 200 status)

Doing so we should be sure that for an approved IIA nobody will ever change values that could impact the nominations.
After that the partners can create a new couple of IIA as usual (IIA CNR - Get - Approval and so on) with the new values.

I apologize for being too verbose in my proposal, but I wished to clarify as much as possible my thoughts.
Thanks for reading, every opinion is welcomed

**Comment by janinamincer-daszkiewicz** [comment] 2022-11-06 12:47
I will try to summarise the proposal of @demilatof expressed in this issue:

1. It is allowed to terminate (close) IIA, but it is not allowed to modify it. After closing IIA  with iid-id=10, if you want to continue you have to create a new IIA e.g. with iia-id=100 with no correlation to IIA with iia-id=10 (at least from the point of view of the network).
2. To handle closing (termination) we introduce four new APIs: 

- IIA Close, IIA Close CNR,
- IIA Close Approval, IIA Close Approval CNR.

Am I right?

**Comment by sascoms** [comment] 2022-11-06 14:55
If I am not misunderstood:

Would not the below be a better and simpler solution?

IIA CNR has a type.
- type: changed/modified/negotiation/closed/terminated/approved etc.


Approval API:
- (better) renamed as Status API or remains the same.
- but with a state: approved/terminated/draft or similar to the ones proposed in related issues.

**Comment by demilatof** [comment] 2022-11-07 00:52
@janinamincer-daszkiewicz 
> 2\. To handle closing (termination) we introduce four new APIs:
> 
> 
>     * IIA Close, IIA Close CNR,
> 
>     * IIA Close Approval, IIA Close Approval CNR.

I don't understand the IIA Close and IIA Close CNR.
To handle closing could be enough IIA Close Approval CNR (that contains even the last academic year of validity) and IIA Close Approval.
I try to guess IIA Close function: could it be to retrieve the closed IIA or the IIA to be closed?
Anyway, the IIA (closed or not) could be always retrieved with IIA GET. If it has been closed, it would contain in both of partner sections this two new elements: 
```
<closed-after-academic-year>2024/25</closed-after-academic-year>
<closed-on-date>timestamp of IIA Close Approval</closed-on-date>
```
That is, in the academic year 2024/25 the IIA will be still valid.

@sascoms 
In my opinion, your solution could be valid to reduce the number of too similar CNRs.
But for approval, or Status API, I think it could be necessary a deeper analysis "what happen if..."
E.g.: The Status API should answer only if before there was the respective CNR?
And moreover, we have to control and respect a statuses sequence, or every institution can do as it wants, skipping statuses or going upward and backward the status sequence, with or without CNR?
Just to understand the level of complication of introducing statuses.

**Comment by janinamincer-daszkiewicz** [comment] 2022-11-07 06:49
> To handle closing could be enough IIA Close Approval CNR (that contains even the last academic year of validity) and IIA Close Approval.

There is nothing like that at the moment. CNR is always a pair to some API. Its purpose is to trigger get on the other side. Nothing else.

So the open question is how the closing would be communicated between the partners.

**Comment by demilatof** [comment] 2022-11-07 22:27
> > To handle closing could be enough IIA Close Approval CNR (that contains even the last academic year of validity) and IIA Close Approval.
> 
> There is nothing like that at the moment. CNR is always a pair to some API. Its purpose is to trigger get on the other side. Nothing else.

May I be wrong, but what does Approval CNR trigger, if not an Approval?
What is the difference between Close Approval CNR and Approval CNR?

> 
> So the open question is how the closing would be communicated between the partners.

I try to explain graphically
![close flow](https://user-images.githubusercontent.com/86968586/200427862-e60bcc0d-0ff8-4fb0-9a7e-859c180d4aed.jpg)

**Comment by kamil-olszewski-uw** [comment] 2022-11-08 05:50
> > > To handle closing could be enough IIA Close Approval CNR (that contains even the last academic year of validity) and IIA Close Approval.
> > 
> > There is nothing like that at the moment. CNR is always a pair to some API. Its purpose is to trigger get on the other side. Nothing else.
> 
> May I be wrong, but what does Approval CNR trigger, if not an Approval? What is the difference between Close Approval CNR and Approval CNR?

By global definition, CNR never contains any information other than the id of the changed object. What you are proposing (completely aside from evaluating your solution) is no longer CNR :-)

**Comment by demilatof** [comment] 2022-11-08 13:45
>By global definition, CNR never contains any information other than the id of the changed object. What you are proposing (completely aside from evaluating your solution) is no longer CNR :-)

Therefore, the IIA Approval CNR is no CNR because there is nothing changed in the IIA?
If the problem is the name, we can change it.
Instead, in my opinion, the problem is the overhead introduced by CNRs if we want to keep them as only a notification of a change.
Because we generate a lot of useless communication:

1. Sending the CNR to tell that there is something to close
2. Listening for a request for more information (with extra controls)
3. Answering with the last academic year of validity (with extra controls)
4. Listening for the close approval
5. Confirming the close approval

Points 2, 3 are useless if we include the information (academic year) in CNR; and doing so everything is more atomic, less information up and down and less possibility that something changes among a transmission and another.
And less controls, because we can never ever think that the received data is correct; every time we exchange data, the receiver must check parameters and manage errors, if present.
And this approach could even simplify other steps in the EWP data flow.

**Comment by kamil-olszewski-uw** [comment] 2022-11-08 14:54
> > By global definition, CNR never contains any information other than the id of the changed object. What you are proposing (completely aside from evaluating your solution) is no longer CNR :-)
> 
> Therefore, the IIA Approval CNR is no CNR because there is nothing changed in the IIA?

IIA Approval CNR API is connected with approvals, not IIAs themeselves. So IIA Approval CNR notifies about change in approval.

**Comment by janinamincer-daszkiewicz** [comment] 2022-11-08 18:51
CNRs are like signals or interrupts. If we change their meaning they will not be CNRs any more.

**Comment by demilatof** [comment] 2022-11-08 21:56
@kamil-olszewski-uw 
> IIA Approval CNR API is connected with approvals, not IIAs themeselves. So IIA Approval CNR notifies about change in approval.

And what change could be in approval? Approval is only for approval; CNR Approval is a signal that we are ready to approve.
A change in approval could only be a "reject" or a "not approved" status; but Approval API doesn't allow this.

@janinamincer-daszkiewicz 
> CNRs are like signals or interrupts. If we change their meaning they will not be CNRs any more.

I don't think that changing the meaning of CNRs could be a great loss.
Their current behavior makes heavy the whole system; we have to double every operation because we cannot immediately add a minimal information.
We have to add more controls because there is a lag between CNR and fetching data.
I think I'm not alone in thinking that the current CNR implementation has limits, as you can see [here](https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/41#issuecomment-1304791864) if I have not misunderstood @sascoms 
You can call this new API as ECNR (Extended CNR) or something completely different, if you'd like better.
But we need a more responsive system in exchanging data, signaling immediately what we are changing,  when it is possible, to obtain an answer immediately in the following call.

**Comment by janinamincer-daszkiewicz** [comment] 2022-11-08 22:11
IIA Approval CNR is sent when we were not ready to approve earlier, but now we are ready to approve. The object 'approval' has been changed so CNR is sent.

If you want our APIs, great, we can discuss that, but please do not call them CNRs.

**Comment by demilatof** [comment] 2022-11-09 00:38
What do you mean "when we were not ready to approve earlier"?
Can we send an IIA Approval without a previous Approval CNR? And how can we be sure that who receives the Approval request is ready to approve?
In our system a previous Approval CNR is mandatory, not optional.
And I think we are right, because "It allows the partners to listen for approvals of their copies of the IIAs."
(but, to be honest, this sentence in not really clear)
https://github.com/erasmus-without-paper/ewp-specs-api-iia-approval-cnr

Moreover, what is the object "approval"?
The API doesn't consider any object approval, but the specifications say "This API allows HEIs to approve agreements sent by their partners".
It's quite intuitive to understand what is the object IIA, but less what is the object approval.
The only "approval object" I see is the XML we send back when the partner calls our "Approval API"; and it is a simple XML with IIA-id and conditions-hash, that is a list of elements to confirm what we approved.
That object does never exist before the first Approval CNR and cannot be changed without changing IIA.
We are still discussing if we can modify an approved IIA; and if an approved IIA could not be modified, we will have no further Approval CNR acceptable nor Approval after the first one.

We have a lot to do, we have a system where a partner by mistake can change data that should not be changed and we have to analyze what could we do to manage this issues, even if these problems should have been faced and solved during the analysis.

But we are more interested in the name we give to APIs.
OK, can we discuss to remove all CNRs and introduce something different more functional to notify a change or to propose a change? Perhaps removing all references to CNRs we would feel our self more free to dig the problems and to find solutions.

**Comment by janinamincer-daszkiewicz** [comment] 2022-11-09 06:57
What do you mean "when we were not ready to approve earlier"?
> Can we send an IIA Approval without a previous Approval CNR? 

Yes

> And how can we be sure that who receives the Approval request is ready to approve?

From the response

> In our system a previous Approval CNR is mandatory, not optional.

Approval CNR is mandatory, but this does not yet mean that the partner cannot proactively send IIA Approval get

>And I think we are right, because "It allows the partners to listen for approvals of their copies of the IIAs."
> (but, to be honest, this sentence in not really clear)
> https://github.com/erasmus-without-paper/ewp-specs-api-iia-approval-cnr

This sentence explains just in point what CNR is for.

> Moreover, what is the object "approval"?

This is my way of explaining the idea, this is the virtual state of IIA meaning that you are ready to approve partner's copy

> The API doesn't consider any object approval, but the specifications say "This API allows HEIs to approve agreements sent by their partners".

I fully agree

> It's quite intuitive to understand what is the object IIA, but less what is the object approval.

I see now that what seemed for me as a useful metaphore is not. Please forget the 'Approval object'

> But we are more interested in the name we give to APIs.

I would not say that we are 'more interested'. Anyway, naming is an important attribute of every specification.

> OK, can we discuss to remove all CNRs and introduce something different more functional to notify a change or to propose a change? 

From the discussion up to now I rather feel that the providers want to limit the changes as much as possible and are not interested in the full redesign. If I am wrong - OK, we can discuss more broad changes.

**Comment by demilatof** [comment] 2022-11-09 10:59
> What do you mean "when we were not ready to approve earlier"?
> 
> > Can we send an IIA Approval without a previous Approval CNR?
> 
> Yes
> 
> > And how can we be sure that who receives the Approval request is ready to approve?
> 
> From the response
> 
> > In our system a previous Approval CNR is mandatory, not optional.
> 
> Approval CNR is mandatory, but this does not yet mean that the partner cannot proactively send IIA Approval get

Well, I think that or the Approval CNR is mandatory or it is not.
If the partner can proactively send IIA Approval get we have to implement a system based upon "polling" from the partner (and we can forget Approval CNR). This means that our system must be redesigned to be able to respond to periodically polling from the partner. 
We can assume that the Approval response is enough to know that who implements the Approval API is ready to approve only if all of us implement the same behavior in our internal system.
We must agree all with this, we cannot implement a strategy and someone else a different one.

[Because specification](https://github.com/erasmus-without-paper/ewp-specs-mobility-flowcharts) say something else; the flowchart is enough clear, I think, and it represents a different approach where before reaching Approval (I marked it as Step 2) you MUST go through Approval CNR (Step 1).
And therefore there is no room to allow the partner to send an Approval request if we haven't send an Approval CNR before.

![iia-approval annotated](https://user-images.githubusercontent.com/86968586/200805323-641100f7-f4eb-4e45-a533-1f283c9dbf98.jpg)

[The same Dashboard](https://wiki.uni-foundation.eu/download/attachments/29853792/Dashboard%20-%20IIAm.pdf?version=1&modificationDate=1649256923038&api=v2) seems to walk through the CNR Approval before considering an Appoval, as described here (page 6) and evidenced in red

> Upon approval, **the partner HEI sends an IIA Approval CNR**, and the creator HEI does an approval request to store its response as proof that the partner HEI approved the IIA


Last but not least, two more considerations about the above flowchart:

1. "_Local id is added iia_id=B13_": this step cannot be performed by the web application by itself, but on input of HEI B representative
2. The current flowchart and APIs allow the HEI B representative to be notified that the two hashes are no more identical, but the HEI A representative will ignore this fact (my red annotation). Therefore, we have the HEI B representative that knows that something has gone wrong and the HEI A representative that is sure that everything has gone well.

**Comment by janinamincer-daszkiewicz** [comment] 2022-11-09 21:56
> Well, I think that or the Approval CNR is mandatory or it is not.

The Approval CNR, as any other Approval is mandatory.
That does not mean that it is forbidden to call IIA Approval get even if CNR has not reached us. In some special situations it may be helpful. For example, our system was down 24 hours due to a power outage. After the system is back in order we check if there are any waiting Approvals since we might have lost some CNRs.

Flowcharts shows one of the possible scenarios, the most typical one.

**Comment by demilatof** [comment] 2022-11-09 22:45
> That does not mean that it is forbidden to call IIA Approval get even if CNR has not reached us

This is clear; but one thing is that CNR has not reached us, another is that it was never sent (successfully or not).
I would accept that you call my IIA Approval provided that I previously sent you a CNR Approval (doesn't matter if you received it or not), because the fact that I tried to send a CNR Approval triggered my system in a listener mode (for Approval).
But it's not clear to me if I have to accept that you call my IIA Approval even if I didn't try to send you a CNR Approval.

If the Approval CNR is mandatory, I think that the system, before accepting an IIA Approval calling, must check if it has previously tried to send a CNR Approval.

**Comment by janinamincer-daszkiewicz** [comment] 2022-11-09 22:48
> But it's not clear to me if I have to accept that you call my IIA Approval even if I didn't try to send you a CNR Approval.
If IIA is in fact ready to be approved - why not?

**Comment by demilatof** [comment] 2022-11-10 01:08
> > But it's not clear to me if I have to accept that you call my IIA Approval even if I didn't try to send you a CNR Approval.
> > If IIA is in fact ready to be approved - why not?

Because if we accept the idea that a system can poll my Approval API to check if we are ready, we have to accept the possibility that all our partners keep polling us until we will be ready, generating useless network traffic.
If they can poll our system only when they receive an Approval CNR (or after a system failure, that should not happen every 5 minutes) the network traffic and the CPU usage drop dramatically, for example.

Moreover, I don't know how each of 5.000 HEIs implements the Approval API.
I can invoke them, and they could answer, but I cannot be sure that behind their answer there is a real will.
For example, a partner can give me an empty answer because they haven't yet sent us an Approval CNR.
Another partner can answer with IIA Id and hash code of an old copy of our IIA, simply because they have matched it with their IIA, even if they are not ready for approval. But they have not implemented any control in Approval API and they answer every time they receive a request, confiding that the partner would have called the API only after the Approval CNR.

There could be several reasons that can allow the Approval API to answer us even if there is not the partner's will, I cannot guess all.
Only if I receive a CNR I can assume that there is the partner will in the approval.

**Comment by umesh-qs** [comment] 2022-11-10 02:55
> > > But it's not clear to me if I have to accept that you call my IIA Approval even if I didn't try to send you a CNR Approval.
> > > If IIA is in fact ready to be approved - why not?
> 
> Because if we accept the idea that a system can poll my Approval API to check if we are ready, we have to accept the possibility that all our partners keep polling us until we will be ready, generating useless network traffic. If they can poll our system only when they receive an Approval CNR (or after a system failure, that should not happen every 5 minutes) the network traffic and the CPU usage drop dramatically, for example.
> 
> Moreover, I don't know how each of 5.000 HEIs implements the Approval API. I can invoke them, and they could answer, but I cannot be sure that behind their answer there is a real will. For example, a partner can give me an empty answer because they haven't yet sent us an Approval CNR. Another partner can answer with IIA Id and hash code of an old copy of our IIA, simply because they have matched it with their IIA, even if they are not ready for approval. But they have not implemented any control in Approval API and they answer every time they receive a request, confiding that the partner would have called the API only after the Approval CNR.
> 
> There could be several reasons that can allow the Approval API to answer us even if there is not the partner's will, I cannot guess all. Only if I receive a CNR I can assume that there is the partner will in the approval.

@demilatof there is no way any API design can help, if your system is not able to handle various scenario. I do not see any reason why there will be a response to "Approval API" without partner's will. It only means that partner's system is not designed properly or is not reliable. If the approval is for old hash then calling system has to verify and ignore it giving proper message to the users. However I am still not clear on what is your concern on this particular topic. Looks like we are digressing from the actual topic.

**Comment by janinamincer-daszkiewicz** [comment] 2022-12-17 13:37
As requested during the Infrastructure Forum meeting on 2022-12-14 I close old issues and will create a new one to finalize the discussion on functionality to terminate/modify approved IIAs.

**Closed as completed by janinamincer-daszkiewicz** 2022-12-17 13:37 UTC
